### ISSUE TITLE
Allow ecomponent:send/2 handle messages of type "reply" without payload

### ISSUE THREAD

**Issue by miquecg** [altenwald/ecomponent#14]
When sending a reply without payload using `ecomponent:send/2` an exception is generated.

`** exception error: no function clause matching exmpp_xml:get_ns_as_atom(undefined) (exmpp/src/core/exmpp_xml.erl, line 900)`

Example reply:
```erlang
{xmlel,'jabber:client',[],iq,
    [
        {xmlattr,undefined,<<"type">>,<<"result">>},
        {xmlattr,undefined,<<"id">>,<<"7982ed0c-67f5-4464-a4d3-50a53b790a0b">>},
        {xmlattr,undefined,<<"from">>,<<"service">>},
        {xmlattr,undefined,<<"to">>,<<"user">>}
    ],
    []
}
```

Same reply sent using `ecomponent:send/3` and passing whatever namespace (2nd argument) will succeed. The namespace is needed by the library for some reason so you have two options, create a reply with a payload to get the namespace from it or use the three arguments version of the send function. In any case the final output will be the same and won't include the namespace.

For convenience of library users sending replies without payload and using the two arguments function would be nice.

**Comment by manuel-rubio** [comment]
@miquecg I've modified the code to accept this kind of send using `ecomponent:send/2`. Thanks for the reporting.
