### ISSUE TITLE
ecomponent_func_test:compare_stanza cannot handle xml document with more than 2 levels of hierachy

### ISSUE THREAD

**Issue by izinin** [altenwald/ecomponent#8]
INPUT: document structure like below

``` xml
            < iq from="shop.im.jongla.im" 
                type="result" 
                to="username01@im.jongla.im/my_device" 
                id="12345">
                <query xmlns="jongla:shop:download-product" category="stickers">
                    <resources>
                        <resource>
                            <fname>boy.zip</fname>
                            <url>..</url>
                        </resource>
                         ...
                    </resources>
                </query>
            </iq>
```

src/ecomponent_func_test.erl:102:<0.358.0>: DIE: {{nocatch,
          {children_length,
              [{children1,
                   [{xmlel,undefined,undefined,"resource",[],
                        [{xmlel,'jongla:shop:download-product',[],fname,[],
                             [{xmlcdata,<<"boy.png">>}]},
                         {xmlel,'jongla:shop:download-product',[],url,[],
                             [{xmlcdata,
                                  <<"http://shop.im.jongla.im.s3.amazonaws.com/shop/devt/stickers/boy/boy.png?AWSAccessKeyId=TestAccessKey">>},
                              {xmlcdata,<<"&">>},
                              {xmlcdata,<<"Expires=1429877295">>},
                              {xmlcdata,<<"&">>},
                              {xmlcdata,<<"Signature=TestSecretKey">>}]}]},
                    {xmlel,undefined,undefined,"resource",[],
                        [{xmlel,'jongla:shop:download-product',[],fname,[],
                             [{xmlcdata,<<"boy.zip">>}]},
                         {xmlel,'jongla:shop:download-product',[],url,[],
                             [{xmlcdata,
                                  <<"http://shop.im.jongla.im.s3.amazonaws.com/shop/devt/stickers/boy/boy.zip?AWSAccessKeyId=TestAccessKey">>},
                              {xmlcdata,<<"&">>},
                              {xmlcdata,<<"Expires=1429877295">>},
                              {xmlcdata,<<"&">>},
                              {xmlcdata,<<"Signature=TestSecretKey">>}]}]},
                    {xmlel,undefined,undefined,"resource",[],
                        [{xmlel,'jongla:shop:download-product',[],fname,[],
                             [{xmlcdata,<<"boy@2x.png">>}]},
                         {xmlel,'jongla:shop:download-product',[],url,[],
                             [{xmlcdata,
                                  <<"http://shop.im.jongla.im.s3.amazonaws.com/shop/devt/stickers/boy/boy%402x.png?AWSAccessKeyId=TestAccessKey">>},
                              {xmlcdata,<<"&">>},
                              {xmlcdata,<<"Expires=1429877295">>},
                              {xmlcdata,<<"&">>},
                              {xmlcdata,<<"Signature=TestSecretKey">>}]}]}]},
              *\* {children2,[]}]}}, **

**Comment by manuel-rubio** [comment]
@izinin actually the error means the number of children is not the same for the stanza you are expecting and the stanza is received.

```
src/ecomponent_func_test.erl:102:<0.358.0>: DIE: {{nocatch,
{children_length,
[{children1,
...
 {children2,[]}...
```

Are you sure the stanza you are receiving is what you are expecting?
